2020-01-17 14:30:18.324 +08:00 [ERR] 在请求controller[Item] 的 action[List] 时产生异常【Unable to resolve service for type 'Apsk.Abstractions.IServiceDiscoveryClient' while attempting to activate 'CatalogItems.API.Services.UserService'.】 ,异常堆栈【   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)】。
2020-01-17 14:31:20.819 +08:00 [ERR] 在请求controller[Item] 的 action[List] 时产生异常【You have executed the generic .Execute<TResult> method on a non-generic FallbackPolicy.  A non-generic FallbackPolicy only defines a fallback action which returns void; it can never return a substitute TResult value.  To use FallbackPolicy to provide fallback TResult values you must define a generic fallback policy FallbackPolicy<TResult>.  For example, define the policy as Policy<TResult>.Handle<Whatever>.Fallback<TResult>(/* some TResult value or Func<..., TResult> */);】 ,异常堆栈【   at Polly.Fallback.FallbackPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Wrap.PolicyWrapEngine.Implementation[TResult](Func`3 func, Context context, CancellationToken cancellationToken, ISyncPolicy outerPolicy, ISyncPolicy innerPolicy)
   at Polly.Wrap.PolicyWrap.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`2 action, Context context)
   at Apsk.ResilienceServiceDiscoveryClient.SendAsync[T](String service, String api, HttpMethod method, Object data, String authorizationToken, String requestId, String authorizationMethod) in F:\Projects\Apsk\src\Apsk\ResilienceServiceDiscoveryClient.cs:line 50
   at CatalogItems.API.Services.UserService.GetNameAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Services\UserService.cs:line 19
   at Projects.API.Application.ItemAppService.ListAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Application\ItemAppService.cs:line 32
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)】。
2020-01-17 14:34:01.335 +08:00 [ERR] 在请求controller[Item] 的 action[List] 时产生异常【You have executed the generic .Execute<TResult> method on a non-generic FallbackPolicy.  A non-generic FallbackPolicy only defines a fallback action which returns void; it can never return a substitute TResult value.  To use FallbackPolicy to provide fallback TResult values you must define a generic fallback policy FallbackPolicy<TResult>.  For example, define the policy as Policy<TResult>.Handle<Whatever>.Fallback<TResult>(/* some TResult value or Func<..., TResult> */);】 ,异常堆栈【   at Polly.Fallback.FallbackPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Wrap.PolicyWrapEngine.Implementation[TResult](Func`3 func, Context context, CancellationToken cancellationToken, ISyncPolicy outerPolicy, ISyncPolicy innerPolicy)
   at Polly.Wrap.PolicyWrap.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`2 action, Context context)
   at Apsk.ResilienceServiceDiscoveryClient.SendAsync(String service, String api, HttpMethod method, Object data, String authorizationToken, String requestId, String authorizationMethod) in F:\Projects\Apsk\src\Apsk\ResilienceServiceDiscoveryClient.cs:line 63
   at CatalogItems.API.Services.UserService.GetNameAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Services\UserService.cs:line 19
   at Projects.API.Application.ItemAppService.ListAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Application\ItemAppService.cs:line 32
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)】。
2020-01-17 14:36:28.619 +08:00 [ERR] 在请求controller[Item] 的 action[List] 时产生异常【You have executed the generic .Execute<TResult> method on a non-generic FallbackPolicy.  A non-generic FallbackPolicy only defines a fallback action which returns void; it can never return a substitute TResult value.  To use FallbackPolicy to provide fallback TResult values you must define a generic fallback policy FallbackPolicy<TResult>.  For example, define the policy as Policy<TResult>.Handle<Whatever>.Fallback<TResult>(/* some TResult value or Func<..., TResult> */);】 ,异常堆栈【   at Polly.Fallback.FallbackPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Wrap.PolicyWrapEngine.Implementation[TResult](Func`3 func, Context context, CancellationToken cancellationToken, ISyncPolicy outerPolicy, ISyncPolicy innerPolicy)
   at Polly.Wrap.PolicyWrap.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`2 action, Context context)
   at Apsk.ResilienceServiceDiscoveryClient.SendAsync(String service, String api, HttpMethod method, Object data, String authorizationToken, String requestId, String authorizationMethod) in F:\Projects\Apsk\src\Apsk\ResilienceServiceDiscoveryClient.cs:line 63
   at CatalogItems.API.Services.UserService.GetNameAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Services\UserService.cs:line 19
   at Projects.API.Application.ItemAppService.ListAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Application\ItemAppService.cs:line 32
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)】。
2020-01-17 14:37:05.331 +08:00 [ERR] 在请求controller[Item] 的 action[List] 时产生异常【An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.】 ,异常堆栈【   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request)
   at Apsk.ResilienceServiceDiscoveryClient.<>c__DisplayClass7_0.<<SendAsync>b__0>d.MoveNext() in F:\Projects\Apsk\src\Apsk\ResilienceServiceDiscoveryClient.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at Apsk.ResilienceServiceDiscoveryClient.SendAsync(String service, String api, HttpMethod method, Object data, String authorizationToken, String requestId, String authorizationMethod) in F:\Projects\Apsk\src\Apsk\ResilienceServiceDiscoveryClient.cs:line 63
   at CatalogItems.API.Services.UserService.GetNameAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Services\UserService.cs:line 19
   at Projects.API.Application.ItemAppService.ListAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Application\ItemAppService.cs:line 32
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)】。
2020-01-17 14:38:16.348 +08:00 [ERR] 在请求controller[Item] 的 action[List] 时产生异常【An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.】 ,异常堆栈【   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request)
   at Apsk.ResilienceServiceDiscoveryClient.<>c__DisplayClass7_0.<<SendAsync>b__0>d.MoveNext() in F:\Projects\Apsk\src\Apsk\ResilienceServiceDiscoveryClient.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at Apsk.ResilienceServiceDiscoveryClient.SendAsync(String service, String api, HttpMethod method, Object data, String authorizationToken, String requestId, String authorizationMethod) in F:\Projects\Apsk\src\Apsk\ResilienceServiceDiscoveryClient.cs:line 63
   at CatalogItems.API.Services.UserService.GetNameAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Services\UserService.cs:line 19
   at Projects.API.Application.ItemAppService.ListAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Application\ItemAppService.cs:line 32
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)】。
2020-01-17 14:39:34.938 +08:00 [ERR] 在请求controller[Item] 的 action[List] 时产生异常【Exception of type 'System.Exception' was thrown.】 ,异常堆栈【   at Apsk.ResilienceServiceDiscoveryClient.<>c__DisplayClass7_0.<<SendAsync>b__0>d.MoveNext() in F:\Projects\Apsk\src\Apsk\ResilienceServiceDiscoveryClient.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at Apsk.ResilienceServiceDiscoveryClient.SendAsync(String service, String api, HttpMethod method, Object data, String authorizationToken, String requestId, String authorizationMethod) in F:\Projects\Apsk\src\Apsk\ResilienceServiceDiscoveryClient.cs:line 63
   at CatalogItems.API.Services.UserService.GetNameAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Services\UserService.cs:line 19
   at Projects.API.Application.ItemAppService.ListAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Application\ItemAppService.cs:line 32
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)】。
2020-01-17 14:39:41.105 +08:00 [ERR] 在请求controller[Item] 的 action[List] 时产生异常【Exception of type 'System.Exception' was thrown.】 ,异常堆栈【   at Apsk.ResilienceServiceDiscoveryClient.<>c__DisplayClass7_0.<<SendAsync>b__0>d.MoveNext() in F:\Projects\Apsk\src\Apsk\ResilienceServiceDiscoveryClient.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at Apsk.ResilienceServiceDiscoveryClient.SendAsync(String service, String api, HttpMethod method, Object data, String authorizationToken, String requestId, String authorizationMethod) in F:\Projects\Apsk\src\Apsk\ResilienceServiceDiscoveryClient.cs:line 63
   at CatalogItems.API.Services.UserService.GetNameAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Services\UserService.cs:line 19
   at Projects.API.Application.ItemAppService.ListAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Application\ItemAppService.cs:line 32
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)】。
2020-01-17 14:39:42.373 +08:00 [ERR] 在请求controller[Item] 的 action[List] 时产生异常【Exception of type 'System.Exception' was thrown.】 ,异常堆栈【   at Apsk.ResilienceServiceDiscoveryClient.<>c__DisplayClass7_0.<<SendAsync>b__0>d.MoveNext() in F:\Projects\Apsk\src\Apsk\ResilienceServiceDiscoveryClient.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at Apsk.ResilienceServiceDiscoveryClient.SendAsync(String service, String api, HttpMethod method, Object data, String authorizationToken, String requestId, String authorizationMethod) in F:\Projects\Apsk\src\Apsk\ResilienceServiceDiscoveryClient.cs:line 63
   at CatalogItems.API.Services.UserService.GetNameAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Services\UserService.cs:line 19
   at Projects.API.Application.ItemAppService.ListAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Application\ItemAppService.cs:line 32
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)】。
2020-01-17 14:39:44.277 +08:00 [ERR] 在请求controller[Item] 的 action[List] 时产生异常【Exception of type 'System.Exception' was thrown.】 ,异常堆栈【   at Apsk.ResilienceServiceDiscoveryClient.<>c__DisplayClass7_0.<<SendAsync>b__0>d.MoveNext() in F:\Projects\Apsk\src\Apsk\ResilienceServiceDiscoveryClient.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at Apsk.ResilienceServiceDiscoveryClient.SendAsync(String service, String api, HttpMethod method, Object data, String authorizationToken, String requestId, String authorizationMethod) in F:\Projects\Apsk\src\Apsk\ResilienceServiceDiscoveryClient.cs:line 63
   at CatalogItems.API.Services.UserService.GetNameAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Services\UserService.cs:line 19
   at Projects.API.Application.ItemAppService.ListAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Application\ItemAppService.cs:line 32
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)】。
2020-01-17 14:39:44.585 +08:00 [ERR] 在请求controller[Item] 的 action[List] 时产生异常【Exception of type 'System.Exception' was thrown.】 ,异常堆栈【   at Apsk.ResilienceServiceDiscoveryClient.<>c__DisplayClass7_0.<<SendAsync>b__0>d.MoveNext() in F:\Projects\Apsk\src\Apsk\ResilienceServiceDiscoveryClient.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at Apsk.ResilienceServiceDiscoveryClient.SendAsync(String service, String api, HttpMethod method, Object data, String authorizationToken, String requestId, String authorizationMethod) in F:\Projects\Apsk\src\Apsk\ResilienceServiceDiscoveryClient.cs:line 63
   at CatalogItems.API.Services.UserService.GetNameAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Services\UserService.cs:line 19
   at Projects.API.Application.ItemAppService.ListAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Application\ItemAppService.cs:line 32
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)】。
2020-01-17 14:39:45.459 +08:00 [ERR] 在请求controller[Item] 的 action[List] 时产生异常【Exception of type 'System.Exception' was thrown.】 ,异常堆栈【   at Apsk.ResilienceServiceDiscoveryClient.<>c__DisplayClass7_0.<<SendAsync>b__0>d.MoveNext() in F:\Projects\Apsk\src\Apsk\ResilienceServiceDiscoveryClient.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at Apsk.ResilienceServiceDiscoveryClient.SendAsync(String service, String api, HttpMethod method, Object data, String authorizationToken, String requestId, String authorizationMethod) in F:\Projects\Apsk\src\Apsk\ResilienceServiceDiscoveryClient.cs:line 63
   at CatalogItems.API.Services.UserService.GetNameAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Services\UserService.cs:line 19
   at Projects.API.Application.ItemAppService.ListAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Application\ItemAppService.cs:line 32
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)】。
2020-01-17 14:39:45.731 +08:00 [ERR] 在请求controller[Item] 的 action[List] 时产生异常【Exception of type 'System.Exception' was thrown.】 ,异常堆栈【   at Apsk.ResilienceServiceDiscoveryClient.<>c__DisplayClass7_0.<<SendAsync>b__0>d.MoveNext() in F:\Projects\Apsk\src\Apsk\ResilienceServiceDiscoveryClient.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at Apsk.ResilienceServiceDiscoveryClient.SendAsync(String service, String api, HttpMethod method, Object data, String authorizationToken, String requestId, String authorizationMethod) in F:\Projects\Apsk\src\Apsk\ResilienceServiceDiscoveryClient.cs:line 63
   at CatalogItems.API.Services.UserService.GetNameAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Services\UserService.cs:line 19
   at Projects.API.Application.ItemAppService.ListAsync() in F:\Projects\Apsk\samples\CatalogItems.API\Application\ItemAppService.cs:line 32
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)】。
